export enum UserRole {
  USER = 'USER',
  COACH = 'COACH',
  GYM_STAFF = 'GYM_STAFF',
  GYM_OWNER = 'GYM_OWNER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE'
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION'
}

export enum GymTier {
  BASIC = 'BASIC',
  PLUS = 'PLUS',
  PREMIUM = 'PREMIUM',
  ELITE = 'ELITE'
}

export enum GymAccessMode {
  MALE_ONLY = 'MALE_ONLY',
  FEMALE_ONLY = 'FEMALE_ONLY',
  MIXED = 'MIXED'
}

export enum CreditLedgerEntryType {
  PLAN_PURCHASE = 'PLAN_PURCHASE',
  TOPUP_PURCHASE = 'TOPUP_PURCHASE',
  CHECKIN_DEBIT = 'CHECKIN_DEBIT',
  REFUND_CREDIT = 'REFUND_CREDIT',
  REFUND_DEBIT = 'REFUND_DEBIT',
  CYCLE_EXPIRATION_SETTLEMENT = 'CYCLE_EXPIRATION_SETTLEMENT',
  ROLLOVER_PRESERVED = 'ROLLOVER_PRESERVED',
  CREDIT_EXPIRATION_EXCESS = 'CREDIT_EXPIRATION_EXCESS',
  EXPIRED_CREDIT = 'EXPIRED_CREDIT',
  CREDIT_BREAKAGE_EVENT = 'CREDIT_BREAKAGE_EVENT',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT'
}

export enum GymPayableEntryType {
  CHECKIN_EARNING = 'CHECKIN_EARNING',
  DISBURSEMENT_PAYA = 'DISBURSEMENT_PAYA',
  DISPUTE_ADJUSTMENT = 'DISPUTE_ADJUSTMENT',
  BONUS_INCENTIVE = 'BONUS_INCENTIVE'
}

export enum CheckinStatus {
  COMPLETED = 'COMPLETED',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED'
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED'
}

export enum SettlementStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED_FOR_PAYA = 'APPROVED_FOR_PAYA',
  PAID = 'PAID',
  REJECTED = 'REJECTED'
}

export enum FraudSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED'
}

export enum PaymentPurpose {
  MEMBERSHIP_PLAN = 'MEMBERSHIP_PLAN',
  CLASS_SINGLE_SESSION = 'CLASS_SINGLE_SESSION',
  COACH_MONTHLY_PLAN = 'COACH_MONTHLY_PLAN'
}

export enum CoachVerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED'
}

export enum ClassVenueType {
  GRAVITY_GYM = 'GRAVITY_GYM',
  PARTNER_GYM = 'PARTNER_GYM',
  EXTERNAL_GYM = 'EXTERNAL_GYM',
  INDEPENDENT_VENUE = 'INDEPENDENT_VENUE',
  OUTDOOR = 'OUTDOOR',
  ONLINE = 'ONLINE'
}

export enum ClassDifficulty {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  ALL_LEVELS = 'ALL_LEVELS'
}

export enum ClassSessionStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum ClassBookingStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
  REFUNDED = 'REFUNDED'
}

export enum ClassAttendanceStatus {
  PENDING = 'PENDING',
  ATTENDED = 'ATTENDED',
  NO_SHOW = 'NO_SHOW',
  EXCUSED = 'EXCUSED'
}

export enum CoachPlanStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED',
  EXHAUSTED = 'EXHAUSTED'
}

export enum CoachPlanUsageAction {
  PURCHASE_INITIAL = 'PURCHASE_INITIAL',
  SESSION_BOOKING = 'SESSION_BOOKING',
  CANCELLATION_RESTORE = 'CANCELLATION_RESTORE',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
  EXPIRATION_REVOKE = 'EXPIRATION_REVOKE'
}

export enum CoachPayableEntryType {
  CLASS_BOOKING_EARNING = 'CLASS_BOOKING_EARNING',
  MONTHLY_PLAN_EARNING = 'MONTHLY_PLAN_EARNING',
  DISBURSEMENT_PAYA = 'DISBURSEMENT_PAYA',
  REFUND_DEDUCTION = 'REFUND_DEDUCTION',
  COMMISSION_ADJUSTMENT = 'COMMISSION_ADJUSTMENT',
  BONUS_INCENTIVE = 'BONUS_INCENTIVE'
}

